# Generated by Django 2.2 on 2019-05-05 14:25

import auditoria.mixins
from django.db import migrations, models
import django.db.models.deletion
import fuente.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('almacen', '0002_auto_20190505_0935'),
        ('moneda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('tags', models.TextField(blank=True, editable=False)),
                ('almacen', models.ForeignKey(help_text='Almacén al que pertenece la cuenta', on_delete=django.db.models.deletion.CASCADE, to='almacen.Almacen', verbose_name='Almacén')),
                ('moneda', models.ForeignKey(help_text='Tipo de moneda de esta cuenta', on_delete=django.db.models.deletion.CASCADE, to='moneda.Moneda', verbose_name='Moneda')),
            ],
            options={
                'verbose_name': 'Nombre',
                'verbose_name_plural': 'Nombres',
            },
            bases=(auditoria.mixins.AuditMixin, models.Model, fuente.utils.Texto),
        ),
    ]
