# Generated by Django 2.2 on 2019-05-05 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cuenta',
            options={'verbose_name': 'Cuenta', 'verbose_name_plural': 'Cuentas'},
        ),
        migrations.RemoveField(
            model_name='cuenta',
            name='codigo',
        ),
        migrations.RemoveField(
            model_name='cuenta',
            name='nombre',
        ),
    ]
