# Generated by Django 2.1.5 on 2019-05-07 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('moneda', '0003_historicalmoneda'),
        ('almacen', '0005_historicalalmacen'),
        ('cuenta', '0002_auto_20190505_1037'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalCuenta',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('tags', models.TextField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('almacen', models.ForeignKey(blank=True, db_constraint=False, help_text='Almacén al que pertenece la cuenta', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='almacen.Almacen', verbose_name='Almacén')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('moneda', models.ForeignKey(blank=True, db_constraint=False, help_text='Tipo de moneda de esta cuenta', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='moneda.Moneda', verbose_name='Moneda')),
            ],
            options={
                'verbose_name': 'historical Cuenta',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
