# Generated by Django 2.1.5 on 2019-05-20 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0003_historicalcuenta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='tags',
            field=models.CharField(blank=True, editable=False, max_length=512),
        ),
        migrations.AlterField(
            model_name='historicalcuenta',
            name='tags',
            field=models.CharField(blank=True, editable=False, max_length=512),
        ),
    ]
