# Generated by Django 2.2.1 on 2019-06-12 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0004_auto_20190520_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='index',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Orden'),
        ),
        migrations.AddField(
            model_name='historicalcuenta',
            name='index',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Orden'),
        ),
    ]
