# Generated by Django 2.2 on 2019-05-05 14:25

import auditoria.mixins
import django.core.validators
from django.db import migrations, models
import fuente.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moneda',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('simbolo', models.CharField(max_length=3, unique=True, verbose_name='Símbolo')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('tasa_compra', models.DecimalField(decimal_places=4, help_text='Tasa en la que la Empresa le compra al cliente.', max_digits=7, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tasa de compra')),
                ('tasa_venta', models.DecimalField(decimal_places=4, help_text='Tasa en la que la Empresa le vende al cliente.', max_digits=7, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tasa de venta')),
                ('tags', models.TextField(blank=True, editable=False)),
            ],
            options={
                'verbose_name': 'Moneda',
                'verbose_name_plural': 'Monedas',
            },
            bases=(auditoria.mixins.AuditMixin, models.Model, fuente.utils.Texto),
        ),
    ]
