# Generated by Django 2.2 on 2019-05-05 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='moneda',
            name='is_principal',
            field=models.BooleanField(default=False, help_text='Indica que esta moneda es la principal (solo puede existir una sola moneda como principal)', verbose_name='¿Es principal?'),
        ),
    ]
