# Generated by Django 2.1.5 on 2019-05-16 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('moneda', '0004_monedatasasupdate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monedatasasupdate',
            options={'verbose_name': 'Actualización de tasas', 'verbose_name_plural': 'Actualizaciones de tasas'},
        ),
    ]
