# Generated by Django 2.1.5 on 2019-05-19 15:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moneda', '0005_auto_20190516_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalmoneda',
            name='tasa_compra',
            field=models.DecimalField(decimal_places=2, help_text='Tasa en la que la Empresa le compra al cliente.', max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tasa de compra'),
        ),
        migrations.AlterField(
            model_name='historicalmoneda',
            name='tasa_venta',
            field=models.DecimalField(decimal_places=2, help_text='Tasa en la que la Empresa le vende al cliente.', max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tasa de venta'),
        ),
        migrations.AlterField(
            model_name='moneda',
            name='tasa_compra',
            field=models.DecimalField(decimal_places=2, help_text='Tasa en la que la Empresa le compra al cliente.', max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tasa de compra'),
        ),
        migrations.AlterField(
            model_name='moneda',
            name='tasa_venta',
            field=models.DecimalField(decimal_places=2, help_text='Tasa en la que la Empresa le vende al cliente.', max_digits=5, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tasa de venta'),
        ),
    ]
