# Generated by Django 2.2 on 2019-05-05 15:21

import auditoria.mixins
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import fuente.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('persona', '0002_auto_20190505_1037'),
        ('almacen', '0003_auto_20190505_1037'),
        ('moneda', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoTipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=10, unique=True, verbose_name='Código')),
                ('nombre', models.CharField(max_length=50, unique=True, verbose_name='Nombre')),
                ('tags', models.TextField(blank=True, editable=False)),
            ],
            options={
                'verbose_name': 'Tipo de documento',
                'verbose_name_plural': 'Tipos de documentos',
            },
            bases=(auditoria.mixins.AuditMixin, models.Model, fuente.utils.Texto),
        ),
        migrations.CreateModel(
            name='Documento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('nota', models.TextField(blank=True, verbose_name='Nota')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=17, verbose_name='Monto')),
                ('tasa', models.DecimalField(decimal_places=4, max_digits=7, verbose_name='Tasa')),
                ('tags', models.TextField(blank=True, editable=False)),
                ('almacen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='almacen.Almacen', verbose_name='Almacén')),
                ('moneda_entrada', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='moneda_entrada', to='moneda.Moneda')),
                ('moneda_salida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='moneda_salida', to='moneda.Moneda')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='persona.Persona', verbose_name='Persona')),
                ('tipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='documento.DocumentoTipo')),
            ],
            options={
                'verbose_name': 'Documento',
                'verbose_name_plural': 'Documentos',
            },
            bases=(auditoria.mixins.AuditMixin, models.Model, fuente.utils.Texto),
        ),
    ]
