# Generated by Django 2.2 on 2019-05-05 16:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='numero',
            field=models.IntegerField(default=10000001, editable=False, unique=True, verbose_name='Número'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='documento',
            name='almacen',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='almacen.Almacen', verbose_name='Almacén'),
        ),
    ]
