# Generated by Django 2.2 on 2019-05-05 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documento', '0002_auto_20190505_1224'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='numero',
            field=models.IntegerField(default=-1, editable=False, unique=True, verbose_name='Número'),
        ),
    ]
