# Generated by Django 2.2 on 2019-05-05 20:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0002_auto_20190505_1037'),
        ('documento', '0003_auto_20190505_1347'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='moneda_entrada',
        ),
        migrations.RemoveField(
            model_name='documento',
            name='moneda_salida',
        ),
        migrations.AddField(
            model_name='documento',
            name='entrada',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='entrada', to='cuenta.Cuenta', verbose_name='Entrada'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documento',
            name='salida',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='salida', to='cuenta.Cuenta', verbose_name='Salida'),
            preserve_default=False,
        ),
    ]
