# Generated by Django 2.2 on 2019-05-05 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documento', '0005_auto_20190505_1645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='entrada',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='entrada_set', to='cuenta.Cuenta', verbose_name='Entrada'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='salida',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='salida_set', to='cuenta.Cuenta', verbose_name='Salida'),
        ),
    ]
