# Generated by Django 2.2 on 2019-05-05 21:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documento', '0006_auto_20190505_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='documento',
            name='monto',
        ),
        migrations.AddField(
            model_name='documento',
            name='monto_entrada',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=17, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto de entrada'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='documento',
            name='monto_salida',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, editable=False, max_digits=17, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto de salida'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='tasa',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=7, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tasa'),
        ),
    ]
