# Generated by Django 2.1.5 on 2019-05-07 16:11

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documento', '0008_documento_cajero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='cajero',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Cajero'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='monto_entrada',
            field=models.DecimalField(decimal_places=2, max_digits=17, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto'),
        ),
    ]
