# Generated by Django 2.1.5 on 2019-05-07 16:13

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('persona', '0003_auto_20190507_1611'),
        ('almacen', '0004_almacen_empresa'),
        ('cuenta', '0002_auto_20190505_1037'),
        ('documento', '0009_auto_20190507_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalDocumento',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('numero', models.IntegerField(db_index=True, default=-1, editable=False, verbose_name='Número')),
                ('fecha', models.DateField(default=django.utils.timezone.now, verbose_name='Fecha')),
                ('fecha_creacion', models.DateTimeField(blank=True, editable=False, verbose_name='Fecha de creación')),
                ('monto_entrada', models.DecimalField(decimal_places=2, max_digits=17, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto')),
                ('monto_salida', models.DecimalField(blank=True, decimal_places=2, default=0, editable=False, max_digits=17, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto de salida')),
                ('tasa', models.DecimalField(decimal_places=4, default=1, max_digits=7, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tasa')),
                ('nota', models.TextField(blank=True, verbose_name='Nota')),
                ('tags', models.TextField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('almacen', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='almacen.Almacen', verbose_name='Almacén')),
                ('cajero', models.ForeignKey(blank=True, db_constraint=False, editable=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Cajero')),
                ('entrada', models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cuenta.Cuenta', verbose_name='Entrada')),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('persona', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='persona.Persona', verbose_name='Persona')),
                ('salida', models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cuenta.Cuenta', verbose_name='Salida')),
                ('tipo', models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='documento.DocumentoTipo')),
            ],
            options={
                'verbose_name': 'historical Documento',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
