# Generated by Django 2.2.1 on 2019-05-10 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documento', '0011_historicaldocumentotipo'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentotipo',
            name='modo',
            field=models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida'), ('TRANSFERENCIA', 'Transferencia'), ('COTIZACION', 'Cotización'), ('ORDEN', 'Orden')], default='ENTRADA', max_length=20, verbose_name='Modo'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='historicaldocumentotipo',
            name='modo',
            field=models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida'), ('TRANSFERENCIA', 'Transferencia'), ('COTIZACION', 'Cotización'), ('ORDEN', 'Orden')], default='ENTRADA', max_length=20, verbose_name='Modo'),
            preserve_default=False,
        ),
    ]
