# Generated by Django 2.2.1 on 2019-05-13 21:39

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documento', '0012_auto_20190510_1537'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='monto_salida',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=17, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto de salida'),
        ),
        migrations.AlterField(
            model_name='documentotipo',
            name='modo',
            field=models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida'), ('TRANSFERENCIA', 'Transferencia'), ('FACTURA', 'Factura'), ('COTIZACION', 'Cotización'), ('ORDEN', 'Orden')], max_length=20, verbose_name='Modo'),
        ),
        migrations.AlterField(
            model_name='historicaldocumento',
            name='monto_salida',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=17, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto de salida'),
        ),
        migrations.AlterField(
            model_name='historicaldocumentotipo',
            name='modo',
            field=models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida'), ('TRANSFERENCIA', 'Transferencia'), ('FACTURA', 'Factura'), ('COTIZACION', 'Cotización'), ('ORDEN', 'Orden')], max_length=20, verbose_name='Modo'),
        ),
    ]
