# Generated by Django 2.2.1 on 2019-05-14 13:47

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documento', '0013_auto_20190513_2139'),
    ]

    operations = [
        migrations.RenameField(
            model_name='documento',
            old_name='tasa',
            new_name='tasa_entrada',
        ),
        migrations.RenameField(
            model_name='historicaldocumento',
            old_name='tasa',
            new_name='tasa_entrada',
        ),
        migrations.AddField(
            model_name='documento',
            name='tasa_salida',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=7, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tasa'),
        ),
        migrations.AddField(
            model_name='historicaldocumento',
            name='tasa_salida',
            field=models.DecimalField(decimal_places=4, default=1, max_digits=7, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tasa'),
        ),
    ]
