# Generated by Django 2.2.1 on 2019-05-14 21:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documento', '0014_auto_20190514_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='tasa_entrada',
            field=models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tasa'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='tasa_salida',
            field=models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tasa (salida)'),
        ),
        migrations.AlterField(
            model_name='historicaldocumento',
            name='tasa_entrada',
            field=models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tasa'),
        ),
        migrations.AlterField(
            model_name='historicaldocumento',
            name='tasa_salida',
            field=models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tasa (salida)'),
        ),
    ]
