# Generated by Django 2.1.5 on 2019-05-16 17:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documento', '0015_auto_20190514_2137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='monto_entrada',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=17, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='tasa_entrada',
            field=models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tasa (entrada)'),
        ),
        migrations.AlterField(
            model_name='historicaldocumento',
            name='monto_entrada',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=17, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto'),
        ),
        migrations.AlterField(
            model_name='historicaldocumento',
            name='tasa_entrada',
            field=models.DecimalField(blank=True, decimal_places=4, default=None, max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tasa (entrada)'),
        ),
    ]
