# Generated by Django 2.1.5 on 2019-05-19 15:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documento', '0017_auto_20190516_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='tasa_entrada',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tasa (entrada)'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='tasa_salida',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tasa (salida)'),
        ),
        migrations.AlterField(
            model_name='historicaldocumento',
            name='tasa_entrada',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tasa (entrada)'),
        ),
        migrations.AlterField(
            model_name='historicaldocumento',
            name='tasa_salida',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tasa (salida)'),
        ),
    ]
