# Generated by Django 2.1.5 on 2019-05-20 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('documento', '0018_auto_20190519_1524'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documento',
            options={'ordering': ['-fecha', '-id'], 'verbose_name': 'Documento', 'verbose_name_plural': 'Documentos'},
        ),
    ]
