# Generated by Django 2.1.5 on 2019-05-20 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documento', '0019_auto_20190520_1530'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='ganancia',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=17, verbose_name='Ganancia'),
        ),
        migrations.AddField(
            model_name='historicaldocumento',
            name='ganancia',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=17, verbose_name='Ganancia'),
        ),
    ]
