# Generated by Django 2.2.1 on 2019-05-22 15:51

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documento', '0021_auto_20190521_1548'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='monto_entrada',
            field=models.DecimalField(decimal_places=2, max_digits=17, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto'),
        ),
        migrations.AlterField(
            model_name='historicaldocumento',
            name='monto_entrada',
            field=models.DecimalField(decimal_places=2, max_digits=17, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto'),
        ),
    ]
