# Generated by Django 2.2.1 on 2019-05-22 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documento', '0022_auto_20190522_1551'),
    ]

    operations = [
        migrations.AddField(
            model_name='documento',
            name='is_print',
            field=models.BooleanField(default=False, verbose_name='¿Se imprimió?'),
        ),
        migrations.AddField(
            model_name='historicaldocumento',
            name='is_print',
            field=models.BooleanField(default=False, verbose_name='¿Se imprimió?'),
        ),
    ]
