# Generated by Django 2.1.5 on 2019-06-09 17:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documento', '0023_auto_20190522_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='monto_entrada',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto que trae el cliente', max_digits=17, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto de entrada'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='monto_salida',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto que se le entregará al cliente', max_digits=17, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto de salida'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='tasa_entrada',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Tasa de entrada (compra)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tasa de entrada'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='tasa_salida',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Tasa de salida (venta)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tasa de salida'),
        ),
        migrations.AlterField(
            model_name='documento',
            name='tipo',
            field=models.ForeignKey(help_text='Tipo de documento', on_delete=django.db.models.deletion.CASCADE, to='documento.DocumentoTipo'),
        ),
        migrations.AlterField(
            model_name='historicaldocumento',
            name='monto_entrada',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto que trae el cliente', max_digits=17, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto de entrada'),
        ),
        migrations.AlterField(
            model_name='historicaldocumento',
            name='monto_salida',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Monto que se le entregará al cliente', max_digits=17, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Monto de salida'),
        ),
        migrations.AlterField(
            model_name='historicaldocumento',
            name='tasa_entrada',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Tasa de entrada (compra)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tasa de entrada'),
        ),
        migrations.AlterField(
            model_name='historicaldocumento',
            name='tasa_salida',
            field=models.DecimalField(blank=True, decimal_places=2, default=None, help_text='Tasa de salida (venta)', max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Tasa de salida'),
        ),
        migrations.AlterField(
            model_name='historicaldocumento',
            name='tipo',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='Tipo de documento', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='documento.DocumentoTipo'),
        ),
    ]
