# Generated by Django 2.2.1 on 2019-06-29 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documento', '0024_auto_20190609_1701'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='tags',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AlterField(
            model_name='historicaldocumento',
            name='tags',
            field=models.CharField(blank=True, max_length=512),
        ),
    ]
