# Generated by Django 2.2.1 on 2019-06-29 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documento', '0025_auto_20190629_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='tags',
            field=models.CharField(blank=True, editable=False, max_length=512),
        ),
        migrations.AlterField(
            model_name='documentotipo',
            name='tags',
            field=models.CharField(blank=True, editable=False, max_length=512),
        ),
        migrations.AlterField(
            model_name='historicaldocumento',
            name='tags',
            field=models.CharField(blank=True, editable=False, max_length=512),
        ),
        migrations.AlterField(
            model_name='historicaldocumentotipo',
            name='tags',
            field=models.CharField(blank=True, editable=False, max_length=512),
        ),
    ]
