"""
Django settings for casacambio project.

Generated by 'django-admin startproject' using Django 2.2.

For more information on this file, see
https://docs.djangoproject.com/en/2.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/2.2/ref/settings/
"""

import os

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/2.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '*n++o(ivabf^8ud4m33))aoxt%6y%4nwh5_mdyn8h#pi9$5=ym'

try:
    import localsettings as local
except (ImportError):
    debug = False
    allowed_hosts = ["*"]
    databases = None
else:
    debug = local.DEBUG
    allowed_hosts = local.ALLOWED_HOSTS
    databases = local.DATABASES


DEBUG = debug

ALLOWED_HOSTS = allowed_hosts


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.contrib.humanize',

    # Aplicaciones externas.
    "dal",
    "dal_select2",
    "simple_history",  # https://django-simple-history.readthedocs.io/en/latest/quick_start.html#install

    # Aplicaciónes del proyecto.
    #"auditoria",
    "base",
    "empresa",
    "almacen",
    "cuenta",
    "documento",
    "moneda",
    "persona",
    "reporte",

    "prestamo",
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    # Auditoria del Sistema (aplicación auditoria)
    "simple_history.middleware.HistoryRequestMiddleware",  # https://django-simple-history.readthedocs.io/en/latest/quick_start.html#install
    #'auditoria.middleware.RequestMiddleware',
]

ROOT_URLCONF = 'app.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, "templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'base.context_processors.context', # New
            ],
        },
    },
]

WSGI_APPLICATION = 'app.wsgi.application'


# Database
# https://docs.djangoproject.com/en/2.2/ref/settings/#databases

sqlite3 = {
    'ENGINE': 'django.db.backends.sqlite3',
    'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
}

mysql_pythonanywhere = {
    'ENGINE': 'django.db.backends.mysql',
    'NAME': 'wilmermartinez$rubiera',
    'USER': 'wilmermartinez',
    'PASSWORD': 'HolaMundo',
    'HOST': 'wilmermartinez.mysql.pythonanywhere-services.com',
    'TEST': {
        'NAME': 'wilmermartinez$test',
    },
}
mysql_localhost = {
    'ENGINE': 'django.db.backends.mysql',
    'NAME': 'casacambio',
    'USER': 'root',
    'PASSWORD': 'HolaMundo',
    'HOST': 'localhost',
    'PORT': '3306',
    'TEST': {
        'NAME': 'test',
    },
}

mysql_from_file = {
    'ENGINE': 'django.db.backends.mysql',
    'OPTIONS': {
        'read_default_file': os.path.join(BASE_DIR, 'mysql.cnf'),
    },
}

if databases:
    DATABASES = databases
else:
    DATABASES = {
        "default": sqlite3,
    }



# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Password validation
# https://docs.djangoproject.com/en/2.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/2.2/topics/i18n/

LANGUAGE_CODE = 'es'

TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = False

USE_TZ = True

THOUSAND_SEPARATOR = ","



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/2.2/howto/static-files/

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, "static"),
    '/var/www/static/',
]

STATIC_URL = '/static/'
#STATIC_ROOT = os.path.join(BASE_DIR, STATIC_URL)

MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, MEDIA_URL)



LOGIN_REDIRECT_URL = "/"
LOGOUT_REDIRECT_URL = "login"