# Generated by Django 2.2.3 on 2019-08-12 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0012_auto_20190629_1626'),
        ('prestamo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prestamo',
            name='almacen',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='almacen.Almacen', verbose_name='Almacén'),
            preserve_default=False,
        ),
    ]
