# Generated by Django 3.0.1 on 2020-03-22 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prestamo', '0002_auto_20190929_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='solicitud',
            name='estado_civil',
            field=models.CharField(choices=[('SOLTERO', 'Soltero'), ('CASADO', 'Casado'), ('UNION_LIBRE', 'Unión libre'), ('OTRO', 'Otro')], max_length=11, verbose_name='Estado civil'),
        ),
    ]
