# Generated by Django 2.2 on 2019-05-05 14:25

import auditoria.mixins
from django.db import migrations, models
import fuente.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identificacion', models.CharField(max_length=20, unique=True, verbose_name='Identificación')),
                ('identificacion_tipo', models.CharField(choices=[('CÉDULA', 'Cédula'), ('PASAPORTE', 'Pasaporte'), ('RNC', 'RNC')], max_length=20, verbose_name='Tipo de identificación')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('razon_social', models.CharField(blank=True, max_length=100, verbose_name='Razón social')),
                ('telefono1', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('telefono2', models.CharField(blank=True, max_length=20, verbose_name='Celular')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo electrónico')),
                ('direccion', models.CharField(blank=True, max_length=256, verbose_name='Dirección')),
                ('persona_de_contacto_nombre', models.CharField(blank=True, max_length=100, verbose_name='Nombre de la persona de contacto')),
                ('persona_de_contacto_identificacion', models.CharField(blank=True, max_length=20, verbose_name='Identificación de la persona de contacto')),
                ('persona_de_contacto_telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono de la persona de contacto')),
                ('tags', models.TextField(blank=True, editable=False)),
            ],
            options={
                'verbose_name': 'Persona',
                'verbose_name_plural': 'Personas',
            },
            bases=(auditoria.mixins.AuditMixin, models.Model, fuente.utils.Texto),
        ),
    ]
