# Generated by Django 2.2 on 2019-05-05 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='identificacion_tipo',
            field=models.CharField(choices=[('CÉDULA', 'Cédula'), ('PASAPORTE', 'Pasaporte'), ('RNC', 'RNC'), ('OTRO', 'Otro')], max_length=20, verbose_name='Tipo de identificación'),
        ),
    ]
