# Generated by Django 2.1.5 on 2019-05-07 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0002_auto_20190505_1037'),
    ]

    operations = [
        migrations.AlterField(
            model_name='persona',
            name='identificacion_tipo',
            field=models.CharField(choices=[('CÉDULA', 'Cédula'), ('PASAPORTE', 'Pasaporte'), ('RNC', 'RNC'), ('OTRO', '')], max_length=20, verbose_name='Tipo de identificación'),
        ),
    ]
