# Generated by Django 2.1.5 on 2019-05-07 17:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import simple_history.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('persona', '0003_auto_20190507_1611'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalPersona',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('identificacion', models.CharField(db_index=True, max_length=20, verbose_name='Identificación')),
                ('identificacion_tipo', models.CharField(choices=[('CÉDULA', 'Cédula'), ('PASAPORTE', 'Pasaporte'), ('RNC', 'RNC'), ('OTRO', '')], max_length=20, verbose_name='Tipo de identificación')),
                ('nombre', models.CharField(max_length=100, verbose_name='Nombre')),
                ('razon_social', models.CharField(blank=True, max_length=100, verbose_name='Razón social')),
                ('telefono1', models.CharField(blank=True, max_length=20, verbose_name='Teléfono')),
                ('telefono2', models.CharField(blank=True, max_length=20, verbose_name='Celular')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Correo electrónico')),
                ('direccion', models.CharField(blank=True, max_length=256, verbose_name='Dirección')),
                ('persona_de_contacto_nombre', models.CharField(blank=True, max_length=100, verbose_name='Nombre de la persona de contacto')),
                ('persona_de_contacto_identificacion', models.CharField(blank=True, max_length=20, verbose_name='Identificación de la persona de contacto')),
                ('persona_de_contacto_telefono', models.CharField(blank=True, max_length=20, verbose_name='Teléfono de la persona de contacto')),
                ('tags', models.TextField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Persona',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
