# Generated by Django 2.2.1 on 2019-06-29 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('persona', '0004_historicalpersona'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalpersona',
            name='tags',
            field=models.CharField(blank=True, editable=False, max_length=512),
        ),
        migrations.AlterField(
            model_name='persona',
            name='tags',
            field=models.CharField(blank=True, editable=False, max_length=512),
        ),
    ]
