# Generated by Django 2.2.6 on 2019-10-30 19:06

from django.db import migrations, models
import fuente.utils


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urlname', models.CharField(help_text='Nombre de la urlpath en la que se mostrará la nota. Ej. base-index', max_length=128)),
                ('titulo', models.CharField(help_text='Nombre legible', max_length=100, verbose_name='Título')),
                ('contenido', models.CharField(max_length=700, verbose_name='Contenido')),
            ],
            bases=(models.Model, fuente.utils.Texto),
        ),
    ]
