# Generated by Django 2.2.1 on 2019-05-24 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Configuracion',
            new_name='ConfiguracionGeneral',
        ),
        migrations.AlterField(
            model_name='configuracioncsv',
            name='caracter_division_celdas',
            field=models.CharField(default=',', max_length=1, verbose_name='Carácter de división de celdas'),
        ),
    ]
