# Generated by Django 2.1.5 on 2019-06-08 20:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moneda', '0006_auto_20190519_1524'),
        ('base', '0003_error'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfiguracionFacturacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moneda_entrada_predeterminada', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cf_moneda_entrada_predeterminada', to='moneda.Moneda', verbose_name='Moneda de entrada predeterminada')),
                ('moneda_salida_predeterminada', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cf_moneda_salida_predeterminada', to='moneda.Moneda', verbose_name='Moneda de salida predeterminada')),
            ],
        ),
    ]
