# Generated by Django 2.1.5 on 2019-06-08 21:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_configuracionfacturacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionfacturacion',
            name='creacion',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
