# Generated by Django 2.1.5 on 2019-06-08 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moneda', '0006_auto_20190519_1524'),
        ('base', '0006_auto_20190608_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionfacturacion',
            name='moneda_entrada_predeterminada',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='moneda.Moneda', verbose_name='Moneda de entrada predeterminada'),
        ),
    ]
