# Generated by Django 2.1.5 on 2019-06-08 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('moneda', '0006_auto_20190519_1524'),
        ('base', '0007_configuracionfacturacion_moneda_entrada_predeterminada'),
    ]

    operations = [
        migrations.AddField(
            model_name='configuracionfacturacion',
            name='moneda_salida_predeterminada',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cf_moneda_salida_predeterminada', to='moneda.Moneda', verbose_name='Moneda de salida predeterminada'),
        ),
    ]
