# Generated by Django 2.2.1 on 2019-06-12 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_configuracionfacturacion_tipo_documento_predeterminado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='configuracionfacturacion',
            name='moneda_entrada_predeterminada',
        ),
        migrations.RemoveField(
            model_name='configuracionfacturacion',
            name='moneda_salida_predeterminada',
        ),
        migrations.RemoveField(
            model_name='configuracionfacturacion',
            name='tipo_documento_predeterminado',
        ),
    ]
