# Generated by Django 2.2.3 on 2019-09-28 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_configuracionfacturacion_tipo_documento_predeterminado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='error',
            name='title',
            field=models.CharField(blank=True, max_length=255, verbose_name='Título'),
        ),
    ]
