# Generated by Django 2.1.5 on 2019-04-09 19:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import fuente.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_comercial', models.CharField(max_length=256, unique=True, verbose_name='Nombre')),
                ('razon_social', models.CharField(max_length=256, unique=True, verbose_name='Razón social')),
                ('identification', models.CharField(max_length=256, unique=True, verbose_name='Identificación')),
                ('identification_type', models.CharField(blank=True, max_length=20, verbose_name='Tipo de identificación')),
                ('logo', models.ImageField(height_field='logo_height', upload_to='empresa/logo/', verbose_name='Logo', width_field='logo_width')),
                ('logo_heigth', models.IntegerField(blank=True, default=None, editable=False, null=True)),
                ('logo_width', models.IntegerField(blank=True, default=None, editable=False, null=True)),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de modificación')),
                ('tags', models.TextField(blank=True, editable=False)),
                ('create_user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empresa_create_user', to=settings.AUTH_USER_MODEL, verbose_name='Usuario creó')),
                ('update_user', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='empresa_update_user', to=settings.AUTH_USER_MODEL, verbose_name='Usuario modificó')),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
            bases=(models.Model, fuente.utils.Texto),
        ),
    ]
