# Generated by Django 2.2.3 on 2019-09-29 02:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import fuente.utils
import simple_history.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True, verbose_name='Nombre')),
                ('razon_social', models.CharField(max_length=255, unique=True, verbose_name='Razón social')),
                ('identificacion', models.CharField(max_length=255, unique=True, verbose_name='Identificación')),
                ('identificacion_tipo', models.CharField(blank=True, max_length=20, verbose_name='Tipo de identificación')),
                ('logo', models.ImageField(blank=True, height_field='logo_height', upload_to='empresa/logo/', verbose_name='Logo', width_field='logo_width')),
                ('logo_height', models.IntegerField(blank=True, default=None, editable=False, null=True)),
                ('logo_width', models.IntegerField(blank=True, default=None, editable=False, null=True)),
                ('tags', models.TextField(blank=True, editable=False)),
            ],
            options={
                'verbose_name': 'Empresa',
                'verbose_name_plural': 'Empresas',
            },
            bases=(models.Model, fuente.utils.Texto),
        ),
        migrations.CreateModel(
            name='HistoricalEmpresa',
            fields=[
                ('id', models.IntegerField(auto_created=True, blank=True, db_index=True, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, max_length=255, verbose_name='Nombre')),
                ('razon_social', models.CharField(db_index=True, max_length=255, verbose_name='Razón social')),
                ('identificacion', models.CharField(db_index=True, max_length=255, verbose_name='Identificación')),
                ('identificacion_tipo', models.CharField(blank=True, max_length=20, verbose_name='Tipo de identificación')),
                ('logo', models.TextField(blank=True, verbose_name='Logo')),
                ('logo_height', models.IntegerField(blank=True, default=None, editable=False, null=True)),
                ('logo_width', models.IntegerField(blank=True, default=None, editable=False, null=True)),
                ('tags', models.TextField(blank=True, editable=False)),
                ('history_id', models.AutoField(primary_key=True, serialize=False)),
                ('history_date', models.DateTimeField()),
                ('history_change_reason', models.CharField(max_length=100, null=True)),
                ('history_type', models.CharField(choices=[('+', 'Created'), ('~', 'Changed'), ('-', 'Deleted')], max_length=1)),
                ('history_user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'historical Empresa',
                'ordering': ('-history_date', '-history_id'),
                'get_latest_by': 'history_date',
            },
            bases=(simple_history.models.HistoricalChanges, models.Model),
        ),
    ]
