# Generated by Django 2.2 on 2019-04-12 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='logo_heigth',
            new_name='logo_height',
        ),
    ]
