# Generated by Django 2.2 on 2019-05-05 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0002_auto_20190412_1634'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='create_user',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='update_date',
        ),
        migrations.RemoveField(
            model_name='empresa',
            name='update_user',
        ),
    ]
