# Generated by Django 2.2 on 2019-05-05 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0003_auto_20190505_0856'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='logo',
            field=models.ImageField(blank=True, height_field='logo_height', upload_to='empresa/logo/', verbose_name='Logo', width_field='logo_width'),
        ),
    ]
