# Generated by Django 2.1.5 on 2019-05-06 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0004_auto_20190505_0935'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='identification',
            new_name='identificacion',
        ),
        migrations.RenameField(
            model_name='empresa',
            old_name='identification_type',
            new_name='identificacion_tipo',
        ),
        migrations.RenameField(
            model_name='empresa',
            old_name='nombre_comercial',
            new_name='nombre',
        ),
    ]
