# Generated by Django 2.2.1 on 2019-06-29 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0006_historicalempresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='tags',
            field=models.CharField(blank=True, editable=False, max_length=512),
        ),
        migrations.AlterField(
            model_name='historicalempresa',
            name='tags',
            field=models.CharField(blank=True, editable=False, max_length=512),
        ),
    ]
