# Generated by Django 2.2.3 on 2019-09-28 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0007_auto_20190629_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='identificacion',
            field=models.CharField(max_length=255, unique=True, verbose_name='Identificación'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='nombre',
            field=models.CharField(max_length=255, unique=True, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='razon_social',
            field=models.CharField(max_length=255, unique=True, verbose_name='Razón social'),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='tags',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='historicalempresa',
            name='identificacion',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Identificación'),
        ),
        migrations.AlterField(
            model_name='historicalempresa',
            name='nombre',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Nombre'),
        ),
        migrations.AlterField(
            model_name='historicalempresa',
            name='razon_social',
            field=models.CharField(db_index=True, max_length=255, verbose_name='Razón social'),
        ),
        migrations.AlterField(
            model_name='historicalempresa',
            name='tags',
            field=models.TextField(blank=True, editable=False),
        ),
    ]
