# Generated by Django 2.2 on 2019-05-05 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='almacen',
            options={'verbose_name': 'Almacén', 'verbose_name_plural': 'Almacenes'},
        ),
        migrations.AddField(
            model_name='almacen',
            name='activo',
            field=models.BooleanField(default=True, verbose_name='Activo'),
        ),
        migrations.AddField(
            model_name='almacen',
            name='codigo',
            field=models.CharField(default='', max_length=10, unique=True, verbose_name='Código'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='almacen',
            name='nombre',
            field=models.CharField(default='', max_length=50, unique=True, verbose_name='Nombre'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='almacen',
            name='tags',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='almacen',
            name='ubicacion',
            field=models.CharField(blank=True, max_length=100, verbose_name='Ubicación'),
        ),
    ]
