# Generated by Django 2.1.5 on 2019-05-06 09:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('empresa', '0004_auto_20190505_0935'),
        ('almacen', '0003_auto_20190505_1037'),
    ]

    operations = [
        migrations.AddField(
            model_name='almacen',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='empresa.Empresa', verbose_name='Empresa'),
            preserve_default=False,
        ),
    ]
