# Generated by Django 2.1.5 on 2019-05-20 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0005_historicalalmacen'),
    ]

    operations = [
        migrations.AddField(
            model_name='almacen',
            name='telefonos',
            field=models.CharField(blank=True, max_length=50, verbose_name='Teléfonos'),
        ),
        migrations.AddField(
            model_name='historicalalmacen',
            name='telefonos',
            field=models.CharField(blank=True, max_length=50, verbose_name='Teléfonos'),
        ),
    ]
