# Generated by Django 2.2.1 on 2019-06-12 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cuenta', '0004_auto_20190520_1719'),
        ('almacen', '0007_auto_20190611_1836'),
    ]

    operations = [
        migrations.AddField(
            model_name='almacen',
            name='salida_predeterminada',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuenta_salida_predeterminada', to='cuenta.Cuenta', verbose_name='Cuenta de salida predeterminada'),
        ),
        migrations.AddField(
            model_name='historicalalmacen',
            name='salida_predeterminada',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cuenta.Cuenta', verbose_name='Cuenta de salida predeterminada'),
        ),
        migrations.AlterField(
            model_name='almacen',
            name='entrada_predeterminada',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cuenta_entrada_predeterminada', to='cuenta.Cuenta', verbose_name='Cuenta de entrada predeterminada'),
        ),
        migrations.AlterField(
            model_name='historicalalmacen',
            name='entrada_predeterminada',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='cuenta.Cuenta', verbose_name='Cuenta de entrada predeterminada'),
        ),
    ]
