# Generated by Django 2.2.1 on 2019-06-12 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documento', '0024_auto_20190609_1701'),
        ('almacen', '0008_auto_20190612_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='almacen',
            name='tipo_documento_predeterminado',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documento.DocumentoTipo', verbose_name='Tipo de documento predeterminado'),
        ),
        migrations.AddField(
            model_name='historicalalmacen',
            name='tipo_documento_predeterminado',
            field=models.ForeignKey(blank=True, db_constraint=False, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='documento.DocumentoTipo', verbose_name='Tipo de documento predeterminado'),
        ),
    ]
