# Generated by Django 2.2.1 on 2019-06-12 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0010_auto_20190612_1708'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='almacen',
            name='entrada_predeterminada',
        ),
        migrations.RemoveField(
            model_name='almacen',
            name='salida_predeterminada',
        ),
        migrations.RemoveField(
            model_name='historicalalmacen',
            name='entrada_predeterminada',
        ),
        migrations.RemoveField(
            model_name='historicalalmacen',
            name='salida_predeterminada',
        ),
    ]
