# Generated by Django 2.2.1 on 2019-06-29 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0011_auto_20190612_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='almacen',
            name='tags',
            field=models.CharField(blank=True, editable=False, max_length=512),
        ),
        migrations.AlterField(
            model_name='historicalalmacen',
            name='tags',
            field=models.CharField(blank=True, editable=False, max_length=512),
        ),
    ]
