# Generated by Django 2.2.3 on 2019-09-28 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('almacen', '0012_auto_20190629_1626'),
    ]

    operations = [
        migrations.AlterField(
            model_name='almacen',
            name='tags',
            field=models.TextField(blank=True, editable=False),
        ),
        migrations.AlterField(
            model_name='historicalalmacen',
            name='tags',
            field=models.TextField(blank=True, editable=False),
        ),
    ]
